kind: Deployment
apiVersion: apps/v1
metadata:
  name: autius-checker
spec:
  selector:
    matchLabels:
      app: autius-checker
  template:
    metadata:
      labels:
        app: autius-checker
    spec:
      containers:
        - name: autius-checker
          image: pinquito/autius-checker
          imagePullPolicy: Always
          volumeMounts:
          - name: env
            mountPath: "/app/.env"
            subPath: env
            readOnly: true
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              cpu: 100m
              memory: 50Mi
      volumes:
      - name: env
        secret:
          secretName: env
      imagePullSecrets:
      - name: dockerhub
