name: Find classes

on:
  schedule:
  - cron: '*/30 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: 'echo "$ENV_FILE" > .env'
        env:
          ENV_FILE: ${{ secrets.ENV_FILE }}
      - uses: addnab/docker-run-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          image: pinquito/autius-checker
          options: -v ${{ github.workspace }}/.env:/app/.env
          run: ./bin/autius-checker
