name: Find classes

on:
  schedule:
  - cron: '*/15 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: 'echo "$ENV_FILE" > .env'
        with:
          ENV_FILE: ${{ secrets.ENV_FILE }}
      - uses: addnab/docker-run-action@v2
        with:
          username: {{ secrets.DOCKER_USERNAME }}
          password: {{ secrets.DOCKER_PASSWORD }}
          image: pinquito/autius-checker
          options: -v ${{ github.workspace }}/.env:/app/.env
